:_module-type: REFERENCE
:stem: asciimath

[id="supported-bias-metrics_{context}"]
= Supported bias metrics

== Demographic parity metrics

Statistical Parity Difference::
+
--
_Statistical Parity Difference_ (SPD) is the difference in the probability of a favorable outcome prediction between unprivileged and privileged groups.  The formal definition of SPD is the following:

[stem]
++++
SPD=p(hat{y}=1|D_u)-p(hat{y}=1|D_p)
++++

* stem:[hat{y}=1] is the favorable outcome.
* stem:[D_u, D_p] are the privileged and unprivileged group data, respectively.

You can interpret SPD values as follows:

* A value of `0` means that the model is behaving fairly for a selected attribute (for example,  race, gender).
* A value in the range  `-0.1` to `0.1` means that the model is reasonably fair for a selected attribute. Instead, you can attribute the difference in probability to other factors, such as the sample size.
* A value outside the range `-0.1` to `0.1` indicates that the model is unfair for a selected attribute.
* A negative value indicates that the model has bias against the unprivileged group.
* A positive value indicates that the model has bias against the privileged group.
--

Disparate Impact Ratio::
+
--
_Disparate Impact Ratio_ (DIR) is the ratio of the probability of a favorable outcome prediction for unprivileged groups to that of privileged groups. The formal definition of DIR is the following:

[stem]
++++
DIR=\frac{p(hat{y}=1|D_u)}{p(hat{y}=1|D_p)}
++++

* stem:[hat{y}=1] is the favorable outcome.
* stem:[D_u, D_p] are the privileged and unprivileged group data, respectively.

You can interpret DIR values as follows:

* A value of `1` means that the model is fair for a selected attribute.
* A value of between `0.8` and `1.2` means that the model is reasonably fair for a selected attribute.
--










//[role='_additional-resources']
//.Additional resources
